import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const C=window.NOSTRIX_STAFF_CONFIG||{},$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const ok=C.SUPABASE_URL&&C.SUPABASE_PUBLISHABLE_KEY&&!C.SUPABASE_URL.includes("PASTE_");
const S={db:null,user:null,profile:null,profiles:[],projects:[],tasks:[],comments:[],links:[],files:[],activity:[],notifications:[],view:"mine",search:"",priority:"all",assignee:"all",project:"all",taskId:null,lang:localStorage.getItem("nostrix_language_v1")==="ar"?"ar":"en",rt:null};
const T={en:{staffWorkspace:"Staff workspace",welcome:"Welcome back.",loginHelp:"Sign in with an approved Nostrix work email.",workEmail:"Work email",sendLink:"Send sign-in link",inviteOnly:"Invite-only access",workspace:"WORKSPACE",teamTasks:"TEAM TASKS",hello:"Hello",dashboardIntro:"Keep track of what needs to be done, who owns it and what is coming up next.",projects:"Projects",newTask:"New task",toDo:"To do",inProgress:"In progress",dueSoon:"Due soon",overdue:"Overdue",completed:"Completed",projectProgress:"PROJECT PROGRESS",activeProjects:"Active projects",manageProjects:"Manage projects",myTasks:"My tasks",allTasks:"All tasks",today:"Today",review:"Review",done:"Done",privateWorkspace:"Private staff workspace",profile:"Profile",signOut:"Sign out",updates:"Updates",notifications:"Notifications",markAllRead:"Mark all read",browserAlerts:"Enable browser alerts",taskDetails:"TASK DETAILS",details:"Details",comments:"Comments",filesLinks:"Files & links",activity:"Activity"},ar:{staffWorkspace:"مساحة فريق العمل",welcome:"مرحباً بعودتك.",loginHelp:"سجّل الدخول ببريد نوستريكس المعتمد.",workEmail:"بريد العمل",sendLink:"إرسال رابط الدخول",inviteOnly:"الدخول للمدعوين فقط",workspace:"مساحة العمل",teamTasks:"مهام الفريق",hello:"مرحباً",dashboardIntro:"تابع المهام والمسؤولين والمواعيد القادمة.",projects:"المشاريع",newTask:"مهمة جديدة",toDo:"للإنجاز",inProgress:"قيد التنفيذ",dueSoon:"موعد قريب",overdue:"متأخرة",completed:"مكتملة",projectProgress:"تقدم المشاريع",activeProjects:"المشاريع النشطة",manageProjects:"إدارة المشاريع",myTasks:"مهامي",allTasks:"كل المهام",today:"اليوم",review:"للمراجعة",done:"تم",privateWorkspace:"مساحة خاصة بالفريق",profile:"الملف الشخصي",signOut:"تسجيل الخروج",updates:"التحديثات",notifications:"الإشعارات",markAllRead:"تحديد الكل كمقروء",browserAlerts:"تفعيل إشعارات المتصفح",taskDetails:"تفاصيل المهمة",details:"التفاصيل",comments:"التعليقات",filesLinks:"الملفات والروابط",activity:"السجل"}};
const tr=k=>T[S.lang][k]||T.en[k]||k, esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const initials=v=>{let p=String(v||"N").split("@")[0].replace(/[._-]/g," ").trim().split(/\s+/);return ((p[0]?.[0]||"N")+(p[1]?.[0]||"")).toUpperCase()};
const toast=m=>{let e=$("#toast");e.textContent=m;e.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>e.hidden=true,2300)};
const days=s=>{if(!s)return null;let a=new Date(s+"T12:00:00"),b=new Date();a.setHours(0,0,0,0);b.setHours(0,0,0,0);return Math.round((a-b)/864e5)};
const due=s=>{let d=days(s);if(d===null)return"No due date";if(d<0)return"Overdue";if(d===0)return"Due today";if(d===1)return"Due tomorrow";return new Intl.DateTimeFormat(S.lang==="ar"?"ar-AE":"en-GB",{day:"numeric",month:"short"}).format(new Date(s+"T12:00:00"))};
const dt=s=>s?new Intl.DateTimeFormat(S.lang==="ar"?"ar-AE":"en-GB",{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(s)):"";
const pf=id=>S.profiles.find(x=>x.user_id===id),pn=id=>pf(id)?.display_name||pf(id)?.email||"Unassigned",pr=id=>S.projects.find(x=>x.id===id);
function applyLang(){document.documentElement.lang=S.lang;document.documentElement.dir=S.lang==="ar"?"rtl":"ltr";localStorage.setItem("nostrix_language_v1",S.lang);$$("[data-t]").forEach(e=>e.textContent=tr(e.dataset.t));$$(".lang").forEach(e=>e.textContent=S.lang==="ar"?"EN":"AR");renderAll()}
function show(id){$("#auth-screen").hidden=id!=="auth-screen";$("#app-screen").hidden=id!=="app-screen"}
async function loadAll(){await Promise.all([loadProfiles(),loadProjects(),loadTasks(),loadNotifs()]);renderAll()}
async function loadProfiles(){let{data}=await S.db.from("profiles").select("*").order("display_name");S.profiles=data||[];fillOptions()}
async function loadProjects(){let{data,error}=await S.db.from("projects").select("*").order("created_at",{ascending:false});if(error)console.error(error);S.projects=data||[];fillOptions()}
async function loadTasks(){let{data,error}=await S.db.from("tasks").select("*").order("created_at",{ascending:false});if(error)console.error(error);S.tasks=data||[]}
async function loadNotifs(){if(!S.user)return;let{data}=await S.db.from("notifications").select("*").eq("user_id",S.user.id).order("created_at",{ascending:false}).limit(40);S.notifications=data||[]}
function fillOptions(){let ppl=S.profiles.map(p=>`<option value="${esc(p.user_id)}">${esc(p.display_name||p.email)}</option>`).join(""),pro=S.projects.filter(p=>p.status==="active").map(p=>`<option value="${esc(p.id)}">${esc(p.client_name?p.client_name+" — "+p.name:p.name)}</option>`).join("");$("#task-assignee").innerHTML=`<option value="">Unassigned</option>${ppl}`;$("#assignee-filter").innerHTML=`<option value="all">All people</option><option value="none">Unassigned</option>${ppl}`;$("#task-project").innerHTML=`<option value="">No project</option>${pro}`;$("#project-filter").innerHTML=`<option value="all">All projects</option><option value="none">No project</option>${pro}`}
function filtered(){let a=[...S.tasks];if(S.view==="mine")a=a.filter(t=>t.assigned_to===S.user.id||t.created_by===S.user.id);if(S.view==="today")a=a.filter(t=>t.status!=="done"&&t.due_date&&days(t.due_date)<=1);if(S.priority!=="all")a=a.filter(t=>t.priority===S.priority);if(S.assignee==="none")a=a.filter(t=>!t.assigned_to);else if(S.assignee!=="all")a=a.filter(t=>t.assigned_to===S.assignee);if(S.project==="none")a=a.filter(t=>!t.project_id);else if(S.project!=="all")a=a.filter(t=>t.project_id===S.project);if(S.search){let q=S.search.toLowerCase();a=a.filter(t=>`${t.title} ${t.details||""} ${pn(t.assigned_to)} ${pr(t.project_id)?.name||""} ${pr(t.project_id)?.client_name||""}`.toLowerCase().includes(q))}return a}
function card(t){let p=pr(t.project_id),d=days(t.due_date),od=d!==null&&d<0&&t.status!=="done",n=pn(t.assigned_to);return`<article class="task" draggable="true" data-id="${t.id}"><div class="task-top"><div class="chips"><span class="chip ${t.priority}">${esc(t.priority)}</span>${od?`<span class="chip overdue">Overdue</span>`:""}</div><button class="task-menu" data-edit="${t.id}"><i class="ph ph-dots-three"></i></button></div>${p?`<div class="project-tag"><i class="ph ph-folder-simple"></i><span>${esc(p.client_name?p.client_name+" · "+p.name:p.name)}</span></div>`:""}<h3>${esc(t.title)}</h3>${t.details?`<p>${esc(t.details)}</p>`:""}<div class="meta"><span class="${od?"overdue":""}"><i class="ph ph-calendar-blank"></i>${esc(due(t.due_date))}</span><span><span class="mini-avatar">${initials(n)}</span>${esc(n)}</span></div></article>`}
function renderTasks(){let a=filtered();["todo","progress","review","done"].forEach(s=>{let b=a.filter(t=>t.status===s);$("#"+s).innerHTML=b.map(card).join("");$("#c-"+s).textContent=b.length});$("#s-todo").textContent=S.tasks.filter(t=>t.status==="todo").length;$("#s-progress").textContent=S.tasks.filter(t=>t.status==="progress").length;$("#s-done").textContent=S.tasks.filter(t=>t.status==="done").length;$("#s-due").textContent=S.tasks.filter(t=>t.status!=="done"&&t.due_date&&days(t.due_date)>=0&&days(t.due_date)<=3).length;$("#s-overdue").textContent=S.tasks.filter(t=>t.status!=="done"&&t.due_date&&days(t.due_date)<0).length;$$("[data-edit]").forEach(b=>b.onclick=e=>{e.stopPropagation();openTask(b.dataset.edit)});$$(".task").forEach(c=>{c.onclick=e=>{if(!e.target.closest("button"))openTask(c.dataset.id)};c.ondragstart=e=>e.dataTransfer.setData("text/plain",c.dataset.id)})}
function renderProjects(){let a=S.projects.filter(p=>p.status==="active");$("#project-cards").innerHTML=a.length?a.map(p=>{let t=S.tasks.filter(x=>x.project_id===p.id),d=t.filter(x=>x.status==="done").length,pc=t.length?Math.round(d/t.length*100):0;return`<button class="project-card" data-project="${p.id}"><header><span><b>${esc(p.name)}</b><br><small>${esc(p.client_name||"")}</small></span><b>${pc}%</b></header><div class="bar"><i style="width:${pc}%"></i></div><small>${d}/${t.length} tasks complete</small></button>`}).join(""):`<div class="empty">No active projects yet.</div>`;$$("[data-project]").forEach(b=>b.onclick=()=>{S.project=b.dataset.project;$("#project-filter").value=S.project;S.view="all";setView("all");renderTasks()})}
function renderNotifs(){let u=S.notifications.filter(n=>!n.is_read).length;$("#notif-badge").hidden=!u;$("#notif-badge").textContent=u;$("#notif-list").innerHTML=S.notifications.length?S.notifications.map(n=>`<button class="notif-item ${n.is_read?"":"unread"}" data-n="${n.id}" data-task="${n.task_id||""}"><i class="notif-dot"></i><span><b>${esc(n.title)}</b><small>${esc(n.body||"")}</small><time>${esc(dt(n.created_at))}</time></span></button>`).join(""):`<div class="empty">No notifications yet.</div>`;$$("[data-n]").forEach(b=>b.onclick=()=>openNotif(b.dataset.n,b.dataset.task))}
function renderAll(){if(!$("#app-screen")||$("#app-screen").hidden)return;fillOptions();renderProjects();renderTasks();renderNotifs()}
function setView(v){S.view=v;$$(".view").forEach(b=>b.classList.toggle("active",b.dataset.view===v))}
async function openTask(id=null,tab="details"){let t=id?S.tasks.find(x=>x.id===id):null;S.taskId=t?.id||null;$("#task-id").value=t?.id||"";$("#task-title").value=t?.title||"";$("#task-details").value=t?.details||"";$("#task-project").value=t?.project_id||"";$("#task-assignee").value=t?.assigned_to||S.user.id;$("#task-due").value=t?.due_date||"";$("#task-priority").value=t?.priority||"medium";$("#task-status").value=t?.status||"todo";$("#task-heading").textContent=t?.title||"New task";$("#delete-task").hidden=!t;$("#task-modal").hidden=false;document.body.style.overflow="hidden";$$(".task-tab").forEach(b=>b.disabled=!t&&b.dataset.tab!=="details");switchTab(t?tab:"details");if(t)await extras(t.id)}
function closeTask(){$("#task-modal").hidden=true;document.body.style.overflow="";S.taskId=null}
function switchTab(n){$$(".task-tab").forEach(b=>b.classList.toggle("active",b.dataset.tab===n));$$(".tab-panel").forEach(p=>{let a=p.dataset.panel===n;p.hidden=!a;p.classList.toggle("active",a)})}
async function saveTask(e){e.preventDefault();let id=$("#task-id").value,old=id?S.tasks.find(t=>t.id===id):null,p={title:$("#task-title").value.trim(),details:$("#task-details").value.trim()||null,project_id:$("#task-project").value||null,assigned_to:$("#task-assignee").value||null,due_date:$("#task-due").value||null,priority:$("#task-priority").value,status:$("#task-status").value};let r=id?await S.db.from("tasks").update(p).eq("id",id).select().single():await S.db.from("tasks").insert({...p,created_by:S.user.id}).select().single();if(r.error)return toast(r.error.message);let t=r.data;if(!id){await log(t.id,"task_created","Task created");if(t.assigned_to)await notify([t.assigned_to],"assigned","You were assigned a task",t.title,t.id,t.project_id)}else{if(old?.assigned_to!==t.assigned_to){await log(t.id,"assignee_changed","Assignee changed");if(t.assigned_to)await notify([t.assigned_to],"assigned","You were assigned a task",t.title,t.id,t.project_id)}if(old?.status!==t.status){await log(t.id,"status_changed","Status changed to "+t.status);if(t.status==="review")await notify([t.created_by,t.assigned_to],"review","Task moved to Review",t.title,t.id,t.project_id);if(t.status==="done")await notify([t.created_by,t.assigned_to],"done","Task completed",t.title,t.id,t.project_id)}}await loadTasks();S.taskId=t.id;$("#task-id").value=t.id;$("#task-heading").textContent=t.title;$("#delete-task").hidden=false;await extras(t.id);renderAll();toast("Task saved")}
async function delTask(){let id=$("#task-id").value;if(!id||!confirm("Delete this task permanently?"))return;let paths=S.files.map(f=>f.storage_path);if(paths.length)await S.db.storage.from("nostrix-staff-files").remove(paths);let{error}=await S.db.from("tasks").delete().eq("id",id);if(error)return toast(error.message);closeTask();await loadTasks();renderAll();toast("Task deleted")}
async function move(id,status){let t=S.tasks.find(x=>x.id===id);if(!t||t.status===status)return;let{data,error}=await S.db.from("tasks").update({status}).eq("id",id).select().single();if(error)return toast(error.message);await log(id,"status_changed","Status changed to "+status);if(status==="review")await notify([data.created_by,data.assigned_to],"review","Task moved to Review",data.title,id,data.project_id);if(status==="done")await notify([data.created_by,data.assigned_to],"done","Task completed",data.title,id,data.project_id);await loadTasks();renderAll()}
async function extras(id){let [a,b,c,d]=await Promise.all([S.db.from("task_comments").select("*").eq("task_id",id).order("created_at"),S.db.from("task_links").select("*").eq("task_id",id).order("created_at",{ascending:false}),S.db.from("task_files").select("*").eq("task_id",id).order("created_at",{ascending:false}),S.db.from("task_activity").select("*").eq("task_id",id).order("created_at",{ascending:false})]);S.comments=a.data||[];S.links=b.data||[];S.files=c.data||[];S.activity=d.data||[];renderExtras()}
function renderExtras(){$("#comment-count").textContent=S.comments.length;$("#resource-count").textContent=S.links.length+S.files.length;$("#comments-list").innerHTML=S.comments.length?S.comments.map(c=>`<article class="comment"><span class="mini-avatar">${initials(pn(c.user_id))}</span><div><header><b>${esc(pn(c.user_id))}</b><time>${esc(dt(c.created_at))}</time></header><p>${esc(c.body)}</p></div></article>`).join(""):`<div class="empty">No comments yet.</div>`;$("#links-list").innerHTML=S.links.map(l=>`<article class="resource-item"><a href="${esc(l.url)}" target="_blank"><i class="ph ph-link"></i><span><b>${esc(l.label||"Link")}</b><small>${esc(l.url)}</small></span></a><button data-dlink="${l.id}"><i class="ph ph-x"></i></button></article>`).join("");$("#files-list").innerHTML=S.files.map(f=>`<article class="resource-item"><button class="resource-open" data-file="${esc(f.storage_path)}"><i class="ph ph-file"></i><span><b>${esc(f.file_name)}</b><small>${Math.round((f.size_bytes||0)/1024)} KB</small></span></button><button data-dfile="${f.id}" data-path="${esc(f.storage_path)}"><i class="ph ph-x"></i></button></article>`).join("");$("#activity-list").innerHTML=S.activity.length?S.activity.map(a=>`<article class="activity-item"><i class="ph ph-clock-counter-clockwise"></i><div><p><b>${esc(pn(a.actor_id))}</b> ${esc(a.detail||a.action)}</p><time>${esc(dt(a.created_at))}</time></div></article>`).join(""):`<div class="empty">No activity yet.</div>`;$$("[data-dlink]").forEach(b=>b.onclick=()=>delLink(b.dataset.dlink));$$("[data-file]").forEach(b=>b.onclick=()=>openFile(b.dataset.file));$$("[data-dfile]").forEach(b=>b.onclick=()=>delFile(b.dataset.dfile,b.dataset.path))}
async function comment(e){e.preventDefault();let body=$("#comment-body").value.trim();if(!S.taskId||!body)return;let{error}=await S.db.from("task_comments").insert({task_id:S.taskId,user_id:S.user.id,body});if(error)return toast(error.message);$("#comment-body").value="";await log(S.taskId,"comment_added","Comment added");let t=S.tasks.find(x=>x.id===S.taskId);await notify([t?.assigned_to,t?.created_by],"comment","New task comment",body.slice(0,100),S.taskId,t?.project_id);await extras(S.taskId);toast("Comment posted")}
async function addLink(e){e.preventDefault();if(!S.taskId)return;let url=$("#link-url").value.trim(),label=$("#link-label").value.trim()||"Link";let{error}=await S.db.from("task_links").insert({task_id:S.taskId,label,url,created_by:S.user.id});if(error)return toast(error.message);$("#link-label").value="";$("#link-url").value="";await log(S.taskId,"link_attached","Link attached: "+label);await extras(S.taskId)}
async function delLink(id){if(!confirm("Remove this link?"))return;await S.db.from("task_links").delete().eq("id",id);await extras(S.taskId)}
async function upload(f){if(!S.taskId||!f)return;if(f.size>20*1024*1024)return toast("File exceeds 20 MB");let safe=f.name.replace(/[^\w.\-]+/g,"_"),path=`${S.taskId}/${crypto.randomUUID()}-${safe}`,u=await S.db.storage.from("nostrix-staff-files").upload(path,f);if(u.error)return toast(u.error.message);let r=await S.db.from("task_files").insert({task_id:S.taskId,file_name:f.name,storage_path:path,mime_type:f.type||null,size_bytes:f.size,created_by:S.user.id});if(r.error){await S.db.storage.from("nostrix-staff-files").remove([path]);return toast(r.error.message)}await log(S.taskId,"file_attached","File attached: "+f.name);await extras(S.taskId);toast("File uploaded")}
async function openFile(path){let{data,error}=await S.db.storage.from("nostrix-staff-files").createSignedUrl(path,3600);if(error)return toast(error.message);window.open(data.signedUrl,"_blank")}
async function delFile(id,path){if(!confirm("Remove this file?"))return;await S.db.storage.from("nostrix-staff-files").remove([path]);await S.db.from("task_files").delete().eq("id",id);await extras(S.taskId)}
async function log(task_id,action,detail,project_id=null){if(S.user)await S.db.from("task_activity").insert({task_id,project_id,actor_id:S.user.id,action,detail})}
async function notify(ids,type,title,body,task_id,project_id){let users=[...new Set((ids||[]).filter(Boolean))].filter(x=>x!==S.user.id);if(users.length)await S.db.from("notifications").insert(users.map(user_id=>({user_id,type,title,body,task_id,project_id})))}
function openProjects(){$("#projects-modal").hidden=false;document.body.style.overflow="hidden";renderProjectList()}
function closeProjects(){$("#projects-modal").hidden=true;document.body.style.overflow="";clearProject()}
function clearProject(){$("#project-id").value="";$("#project-name").value="";$("#project-client").value="";$("#project-due").value="";$("#project-status").value="active"}
function renderProjectList(){$("#projects-list").innerHTML=S.projects.map(p=>`<article class="project-row"><div><strong>${esc(p.name)}</strong><br><small>${esc(p.client_name||"")}</small></div><small>${S.tasks.filter(t=>t.project_id===p.id).length} tasks</small><span class="status">${esc(p.status)}</span><div><button class="text-btn" data-ep="${p.id}">Edit</button><button class="text-btn" data-tp="${p.id}">${p.status==="active"?"Archive":"Restore"}</button></div></article>`).join("");$$("[data-ep]").forEach(b=>b.onclick=()=>editProject(b.dataset.ep));$$("[data-tp]").forEach(b=>b.onclick=()=>toggleProject(b.dataset.tp))}
function editProject(id){let p=pr(id);$("#project-id").value=id;$("#project-name").value=p.name;$("#project-client").value=p.client_name||"";$("#project-due").value=p.due_date||"";$("#project-status").value=p.status}
async function saveProject(e){e.preventDefault();let id=$("#project-id").value,p={name:$("#project-name").value.trim(),client_name:$("#project-client").value.trim()||null,due_date:$("#project-due").value||null,status:$("#project-status").value};let r=id?await S.db.from("projects").update(p).eq("id",id):await S.db.from("projects").insert({...p,created_by:S.user.id});if(r.error)return toast(r.error.message);clearProject();await loadProjects();renderAll();renderProjectList();toast("Project saved")}
async function toggleProject(id){let p=pr(id),status=p.status==="active"?"archived":"active";await S.db.from("projects").update({status}).eq("id",id);await loadProjects();renderAll();renderProjectList()}
function openProfile(){$("#profile-name").value=S.profile.display_name||"";$("#profile-role").value=S.profile.job_title||"";$("#profile-modal").hidden=false;document.body.style.overflow="hidden"}
async function saveProfile(e){e.preventDefault();let{data,error}=await S.db.from("profiles").update({display_name:$("#profile-name").value.trim(),job_title:$("#profile-role").value.trim()||null}).eq("user_id",S.user.id).select().single();if(error)return toast(error.message);S.profile=data;await loadProfiles();uiUser();$("#profile-modal").hidden=true;document.body.style.overflow=""}
function uiUser(){let n=S.profile?.display_name||S.user.email.split("@")[0];$("#user-name").textContent=n;$("#user-email").textContent=S.user.email;$("#hello-name").textContent=n.split(" ")[0];$("#avatar").textContent=initials(n)}
async function openNotif(id,task){await S.db.from("notifications").update({is_read:true}).eq("id",id);await loadNotifs();renderNotifs();$("#notif-panel").hidden=true;if(task)openTask(task)}
async function markRead(){await S.db.from("notifications").update({is_read:true}).eq("user_id",S.user.id).eq("is_read",false);await loadNotifs();renderNotifs()}
async function browserAlerts(){if("Notification"in window&&await Notification.requestPermission()==="granted")toast("Browser alerts enabled")}
async function login(e){e.preventDefault();let email=$("#email").value.trim().toLowerCase(),domain=(C.ALLOWED_EMAIL_DOMAIN||"nostrix.ae").toLowerCase();if(!email.endsWith("@"+domain))return toast("Use an approved Nostrix work email");let{error}=await S.db.auth.signInWithOtp({email,options:{shouldCreateUser:false,emailRedirectTo:location.origin+(C.STAFF_PATH||"/staff/")}});$("#auth-message").textContent=error?"If approved, check your work inbox.":"Check your work inbox for the secure sign-in link."}
async function enter(session){S.user=session.user;let{data}=await S.db.from("profiles").select("*").eq("user_id",S.user.id).maybeSingle();if(!data){await S.db.auth.signOut();return show("auth-screen")}S.profile=data;show("app-screen");await loadAll();uiUser();subscribe()}
async function subscribe(){if(S.rt)await S.db.removeChannel(S.rt);S.rt=S.db.channel("nostrix-v3").on("postgres_changes",{event:"*",schema:"public",table:"tasks"},async()=>{await loadTasks();renderAll()}).on("postgres_changes",{event:"*",schema:"public",table:"projects"},async()=>{await loadProjects();renderAll()}).on("postgres_changes",{event:"INSERT",schema:"public",table:"notifications",filter:`user_id=eq.${S.user.id}`},async p=>{await loadNotifs();renderNotifs();if(Notification?.permission==="granted"&&document.hidden)new Notification(p.new.title,{body:p.new.body||"",icon:"/favicon.png"})}).subscribe()}
async function signout(){if(S.rt)await S.db.removeChannel(S.rt);await S.db.auth.signOut();show("auth-screen")}
function bind(){$$(".lang").forEach(b=>b.onclick=()=>{S.lang=S.lang==="ar"?"en":"ar";applyLang()});$("#login-form").onsubmit=login;$("#new-task").onclick=()=>openTask();$("#task-form").onsubmit=saveTask;$("#delete-task").onclick=delTask;$$("[data-close-task]").forEach(b=>b.onclick=closeTask);$$(".task-tab").forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$("#comment-form").onsubmit=comment;$("#link-form").onsubmit=addLink;$("#file-input").onchange=e=>{if(e.target.files[0])upload(e.target.files[0]);e.target.value=""};$("#projects-btn").onclick=$("#manage-projects").onclick=openProjects;$$("[data-close-projects]").forEach(b=>b.onclick=closeProjects);$("#project-form").onsubmit=saveProject;$("#project-clear").onclick=clearProject;$("#edit-profile").onclick=()=>{$("#profile-menu").hidden=true;openProfile()};$$("[data-close-profile]").forEach(b=>b.onclick=()=>{$("#profile-modal").hidden=true;document.body.style.overflow=""});$("#profile-form").onsubmit=saveProfile;$("#signout").onclick=signout;$("#refresh-btn").onclick=async()=>{await loadAll();toast("Refreshed")};$("#profile-btn").onclick=()=>$("#profile-menu").hidden=!$("#profile-menu").hidden;$("#notif-btn").onclick=()=>$("#notif-panel").hidden=!$("#notif-panel").hidden;$("#mark-read").onclick=markRead;$("#enable-browser").onclick=browserAlerts;$$(".view").forEach(b=>b.onclick=()=>{setView(b.dataset.view);renderTasks()});$("#search").oninput=e=>{S.search=e.target.value.trim();renderTasks()};$("#priority-filter").onchange=e=>{S.priority=e.target.value;renderTasks()};$("#assignee-filter").onchange=e=>{S.assignee=e.target.value;renderTasks()};$("#project-filter").onchange=e=>{S.project=e.target.value;renderTasks()};$$(".column").forEach(c=>{c.ondragover=e=>e.preventDefault();c.ondrop=e=>{e.preventDefault();move(e.dataTransfer.getData("text/plain"),c.dataset.status)}})}
document.addEventListener("DOMContentLoaded",async()=>{$("#year").textContent=new Date().getFullYear();bind();applyLang();if(!ok)return show("auth-screen");S.db=createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY);let{data:{session}}=await S.db.auth.getSession();session?await enter(session):show("auth-screen");S.db.auth.onAuthStateChange(async(e,s)=>{if(e==="SIGNED_IN"&&s)await enter(s);if(e==="SIGNED_OUT")show("auth-screen")})});